# Generated by Django 3.2.3 on 2021-05-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tood',
            new_name='Todo',
        ),
    ]
